# fly.toml file generated for hyperized-weather on 2023-03-11T02:17:42+01:00

app = "hyperized-weather"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
